version: '2'

services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/project
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    image: php:7-fpm
    volumes:
      - ./:/project
    networks:
      - code-network

networks:
  code-network:
    driver: bridge