<!doctype html>
<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta charset="utf-8" />
		<meta name="msapplication-TileColor" content="#da532c">
		<meta name="theme-color" content="#ffffff">

		<title>Wyvern Robotics - Team 6513</title>

		<link rel="apple-touch-icon" sizes="76x76" href="images/apple-touch-icon.png">
		<link rel="icon" type="image/png" sizes="32x32" href="images/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="16x16" href="images/favicon-16x16.png">
		<link rel="mask-icon" href="images/safari-pinned-tab.svg" color="#5bbad5">


		<link rel="stylesheet" href="bower_components/components-font-awesome/css/fontawesome-all.min.css" />
		<!-- <link rel="stylesheet" href="bower_components/jquery-ui/themes/cupertino/jquery-ui.min.css" /> -->
		<link rel="stylesheet" href="bower_components/sass-bootstrap/dist/css/bootstrap.min.css" />
		<!-- <link rel="stylesheet" href="bower_components/jquery-ui/themes/cupertino/theme.css" /> -->
		<link rel="stylesheet" href="bower_components/load-awesome/css/cog.min.css" />

		<link rel="stylesheet" href="css/styles.css" />

		<style>
			/* some styling could go here */
		</style>

		<script>
			/* some config should be here */
			var CONFIG = {
				frameRate: 15,
				cameras: {
					cam0: 'http://<?php echo $server['SERVER_ADDR'] ?>/cameras/cam0.mjpeg',
					cam1: 'http://<?php echo $server['SERVER_ADDR'] ?>/cameras/cam1.mjpeg'
				},
				/* cameras: {
					cam0: 'http://192.168.1.162/oneplus',
					cam1: 'http://192.168.1.162/oneplus',
				} */
			}
		</script>

		<script src="bower_components/jquery/dist/jquery.min.js"></script>
  	<script src="bower_components/tooltip.js/index.js"></script>
		<script src="bower_components/sass-bootstrap/dist/js/bootstrap.min.js"></script>
		<script src="bower_components/jsrender/jsrender.min.js"></script>

		<script id="vidButton" type="text/x-jsrender">
			<button draggable="true" type="button" class="btn btn-sm btn-outline-secondary">
				<i class="fas fa-video"></i> {{:name}}
			</button>
		</script>

		<script id="vidCanvas" type="text/x-jsrender">
		<div class="vidCanvas row">
			<div class="col-md-3">
				<div class="card mb-3 box-shadow">
					<p class="lead">{{:element}}</p>
				</div>
			</div>
		</div>
		</script>

		<script src="js/wyvern.js"></script>
	</head>
	<body>

<main role="main">

  <section class="jumbotron text-center">
	<div class="container">
		<h3 class="jumbotron-heading">Available Camera Streams</h3>
		<div class="album py-5 bg-light">
			<div class="container">
				<div class="row">
					<div class="col-md-6">Remote:</div>
					<div class="col-md-6">Local:</div>
				</div>
				<div class="row">
					<div class="button_remote col-md-6">
						<button type="button" class="btn btn-sm btn-outline-secondary">
							<i class="fas fa-video"></i>
						</button>
					</div>
					<div class="button_local col-md-6">
						<button type="button" class="btn btn-sm btn-outline-secondary">
							<i class="fas fa-video"></i>
						</button>
					</div>
				</div>				
			</div>
		</div>
	</div>
  </section>

  <div class="album py-5 bg-light">
		<div class="container">
			<div data-type="empty" class="vidCanvas row">
				<div class="col-md-3">
					<div class="card mb-3 box-shadow">
						<p class="lead">Drop a camera here.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>


</body>
</html>